version: "3.8"
services:
  backend:
    container_name: backend_wms_<city>
    image: 766423106308.dkr.ecr.ap-southeast-1.amazonaws.com/be-wms-pdam:<image-tag>
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    networks:
      - wms_pdam_<city>
    restart: always
    logging:
      driver: json-file
      options:
        "max-size": "10m"
        "max-file": "5"

networks:
  wms_pdam_<city>: